language: node_js
node_js:
  - "node"
env:
  - DIR="${TRAVIS_BUILD_DIR}/backend"
  - DIR="${TRAVIS_BUILD_DIR}/frontend"
install:
  - cd "$DIR" && npm install
script:
  - cd "$DIR" && npm run --silent eslint
  - cd "$DIR" && npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
