language: node_js
node_js:
  - "node"
env:
  - DIR="backend" SRCPATH="${TRAVIS_BUILD_DIR}/${DIR}"
  - DIR="frontend" SRCPATH="${TRAVIS_BUILD_DIR}/${DIR}"
install:
  - cd "$SRCPATH" && npm install
script:
  - cd "$SRCPATH" && npm run --silent eslint
  - cd "$SRCPATH" && npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js $DIR
